name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # unit tests use the ambient OIDC credential
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: test
        run: make test INSTALL_EXTRA=test
