name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # unit tests use the ambient OIDC credential
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: test
        run: make test INSTALL_EXTRA=test
